#!/usr/bin/env node

/**
 * Build-time script: computes aHash + color histogram for every reference image
 * in references/motherboard/ and writes src/data/markerReferences.js.
 *
 * Run:  node tools/generateMarkerHashes.js
 */

const fs = require('fs');
const path = require('path');
const sharp = require('sharp');

const REFS_DIR = path.resolve(__dirname, '..', 'references', 'motherboard');
const OUT_FILE = path.resolve(__dirname, '..', 'src', 'data', 'markerReferences.js');
const HASH_BITS = 256; // 16×16 grid = 256 bits

// Hash threshold: max Hamming distance for aHash match
// Set to max intra-reference distance + margin
const HASH_THRESHOLD = 140;

// Color histogram: percentage of green-blue pixels (hue 90°–210°)
// Motherboards have green/blue PCB; non-motherboards won't
// Store min/max range from reference images
const COLOR_MIN = 10; // min % of green-blue pixels expected
const COLOR_MAX = 80; // max % of green-blue pixels expected

async function computeAHash(imagePath) {
  const { data } = await sharp(imagePath)
    .resize(16, 16, { fit: 'fill' })
    .greyscale()
    .raw()
    .toBuffer({ resolveWithObject: true });

  let avg = 0;
  for (let i = 0; i < 256; i++) avg += data[i];
  avg /= 256;

  let hash = 0n;
  for (let i = 0; i < 256; i++) {
    if (data[i] > avg) hash |= 1n << BigInt(i);
  }
  return hash.toString(16).padStart(HASH_BITS / 4, '0');
}

function rgbToHsl(r, g, b) {
  r /= 255; g /= 255; b /= 255;
  const max = Math.max(r, g, b);
  const min = Math.min(r, g, b);
  const d = max - min;
  let h = 0;
  if (d !== 0) {
    if (max === r) h = ((g - b) / d) % 6;
    else if (max === g) h = (b - r) / d + 2;
    else h = (r - g) / d + 4;
    h = Math.round(h * 60);
    if (h < 0) h += 360;
  }
  const l = (max + min) / 2;
  const s = d === 0 ? 0 : d / (1 - Math.abs(2 * l - 1));
  return { h, s, l };
}

function computeColorHistogram(imagePath) {
  return sharp(imagePath)
    .resize(32, 32, { fit: 'fill' })
    .raw()
    .toBuffer({ resolveWithObject: true })
    .then(({ data, info }) => {
      const pixels = info.width * info.height;
      let greenBlueCount = 0;
      for (let i = 0; i < pixels; i++) {
        const r = data[i * 3];
        const g = data[i * 3 + 1];
        const b = data[i * 3 + 2];
        const { h, s } = rgbToHsl(r, g, b);
        // Green-blue hue range (90°–210°) with saturation > 0.15
        if (h >= 90 && h <= 210 && s > 0.15) greenBlueCount++;
      }
      return Math.round((greenBlueCount / pixels) * 100);
    });
}

function hammingDistance(a, b) {
  const xor = BigInt(`0x${a}`) ^ BigInt(`0x${b}`);
  return xor.toString(2).split('1').length - 1;
}

async function main() {
  if (!fs.existsSync(REFS_DIR)) {
    console.error(`References directory not found: ${REFS_DIR}`);
    process.exit(1);
  }

  const files = fs.readdirSync(REFS_DIR)
    .filter(f => /\.(jpe?g|png)$/i.test(f))
    .sort();

  if (files.length === 0) {
    console.error('No reference images found in', REFS_DIR);
    process.exit(1);
  }

  console.log(`Processing ${files.length} reference images…\n`);

  const hashes = [];
  const colorRatios = [];

  for (const file of files) {
    const fullPath = path.join(REFS_DIR, file);
    const [hash, colorPct] = await Promise.all([
      computeAHash(fullPath),
      computeColorHistogram(fullPath),
    ]);
    hashes.push(hash);
    colorRatios.push(colorPct);
    console.log(`  ${file} → hash=${hash}  greenBlue=${colorPct}%`);
  }

  // Validate hash distances
  let maxHashDist = 0;
  for (let i = 0; i < hashes.length; i++) {
    for (let j = i + 1; j < hashes.length; j++) {
      const d = hammingDistance(hashes[i], hashes[j]);
      if (d > maxHashDist) maxHashDist = d;
    }
  }

  // Validate color range
  const minColor = Math.min(...colorRatios);
  const maxColor = Math.max(...colorRatios);

  console.log(`\nHash: max intra-distance = ${maxHashDist} (threshold: ${HASH_THRESHOLD})`);
  console.log(`Color: greenBlue range = ${minColor}%–${maxColor}% (accepted: ${COLOR_MIN}%–${COLOR_MAX}%)`);

  if (maxHashDist >= HASH_THRESHOLD) {
    console.warn('⚠  Hash threshold too tight — raise HASH_THRESHOLD.');
  }
  if (minColor < COLOR_MIN || maxColor > COLOR_MAX) {
    console.warn('⚠  Color range outside bounds — adjust COLOR_MIN/COLOR_MAX.');
  }

  const out = `// Auto-generated by tools/generateMarkerHashes.js — do not edit manually.
// Source: references/motherboard/*.jpg

// aHash (16×16 = 256 bits) for each reference image
export const hashes = ${JSON.stringify(hashes, null, 2)};

// Hamming distance ≤ this value → hash match
export const hashThreshold = ${HASH_THRESHOLD};

// Expected green-blue pixel percentage range for motherboard PCB
export const colorRange = { min: ${COLOR_MIN}, max: ${COLOR_MAX} };
`;
  fs.writeFileSync(OUT_FILE, out, 'utf8');
  console.log(`\nWrote ${OUT_FILE}`);
}

main().catch(err => {
  console.error(err);
  process.exit(1);
});
